name: docker-build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.pdf'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
