name: Build Docker Image

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.pdf'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.pdf'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hc-pdf-server
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
