name: Build Docker Image

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.pdf'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.pdf'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: uyamazak/hc-pdf-server
          tag_with_ref: true
